# Site settings
title:                  "Michael Caplan's Web Existence"
description:            "This site is blatant self promotion. I'm a bit embarassed
                         about its existence but that's how it goes..."
email:                  "michael_caplan@brown.edu"
